server:
  port: 9000
spring:
  application:
    name: gateway-server #应用名,同一实例下的集群要相同
  cloud:
    gateway:
      #使用服务id服务名转发
      discovery:
        locator:
          enabled: true #是否开启基于服务名发现的路由规则,通过serviceId转发到具体的服务名实例,默认是关闭
          lower-case-service-id: true #是否将服务名小写,默认是关闭
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: #下行是注册到服务注册中心
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/